config/routes.rb
ProgrammingTrainer::Application.routes.draw do
  resources :problems do
    resources :solutions, :only => [:index, :create]
  end

  get "sessions/new"

  post "sessions/create"

  match "sessions/destroy", :via => :delete

  resources :users

  root :to => "problems#index"
  

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :cod, :description, :input_format, :output_format, :title, :test_cases_attributes
  
  validates :cod, :description, :input_format, :output_format, :title, :presence => true
  validates :cod, :uniqueness => true
  validate :one_test_case_at_least
  
  has_many :test_cases, :inverse_of => :problem
  has_many :solutions, :inverse_of => :problem, :order => :created_at
  has_many :users, :through => :solutions
  
  accepts_nested_attributes_for :test_cases, 
	:allow_destroy => true, 
	:reject_if => Proc.new{ |attrs| attrs[:title].blank? && attrs[:input].blank? && attrs[:output].blank? && attrs[:max_time].blank? }
	
  private
  
  def one_test_case_at_least
    errors.add(:base, "Debe haber al menos un caso de prueba para el problema") if test_cases.empty?
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new
	2.times { @problem.test_cases.build }
	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
	@problem.test_cases.build
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])
	
    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
	    @problem.test_cases.build if @problem.test_cases.empty?
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod %><br />
    <%= f.text_field :cod %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :input_format %><br />
    <%= f.text_area :input_format %>
  </div>
  <div class="field">
    <%= f.label :output_format %><br />
    <%= f.text_area :output_format %>
  </div>
  
  <div class="test-cases">
    <h3>Casos de prueba</h3>
    <%= f.fields_for :test_cases do |test_case_form| %>
      <div class="test-case" style="margin: 20px">
      
        <div>
          <%= test_case_form.label :title, 'Titulo:' %>
          <%= test_case_form.text_field :title %>
        </div>
        
        <div>
          <%= test_case_form.label :input, 'Archivo de entrada:' %>
          <%= test_case_form.file_field :input %>
        </div>        
        
        <div>
          <%= test_case_form.label :output, 'Archivo de salida:' %>
          <%= test_case_form.file_field :output %>
        </div>
        
        <div>
          <%= test_case_form.label :max_time, 'Tiempo maximo (s):' %>
          <%= test_case_form.number_field :max_time %>
        </div>

        <% unless test_case_form.object.nil? || test_case_form.object.new_record? %>
          <div>
            <%= test_case_form.label :_destroy, 'Remove:' %>
            <%= test_case_form.check_box :_destroy %>
          </div>
        <% end %>        
      </div>
  <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<h1>Listing problems</h1>

<table>
  <tr>
    <th>Cod</th>
    <th>Title</th>
    <th>Description</th>
    <th>Input format</th>
    <th>Output format</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @problems.each do |problem| %>
  <tr>
    <td><%= problem.cod %></td>
    <td><%= problem.title %></td>
    <td><%= problem.description %></td>
    <td><%= problem.input_format %></td>
    <td><%= problem.output_format %></td>
    <td><%= link_to 'Show', problem %></td>
    <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
    <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod:</b>
  <%= @problem.cod %>
</p>

<p>
  <b>Title:</b>
  <%= @problem.title %>
</p>

<p>
  <b>Description:</b>
  <%= @problem.description %>
</p>

<p>
  <b>Input format:</b>
  <%= @problem.input_format %>
</p>

<p>
  <b>Output format:</b>
  <%= @problem.output_format %>
</p>

<p>
  <%= link_to "Soluciones", problem_solutions_path(@problem) %>
</p>

<%= render :partial => "solutions/form", :locals => { :problem => @problem } %>

<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>