config/routes.rb
ProgrammingTrainer::Application.routes.draw do
  resources :problems do
    resources :solutions, :only => [:index, :create]
  end

  get "sessions/new"

  post "sessions/create"

  match "sessions/destroy", :via => :delete

  resources :users

  root :to => "problems#index"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProgrammingTrainer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div id="header-wrapper">
      <div id="logo">
        <a href="/">
          <%= image_tag("rails.png", :alt => "Programming Trainer") %> 
        </a>
      </div>
      <div id="menu">
        <ul>
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "Users" , users_path %>
          </li>
        </ul>
      </div>
    </div>
    <!-- end #header -->
    <div id="page">
      <div id="page-bgtop">
        <div id="page-bgbtm">
          <div id="content">
            <div class="alert">
				<%= (render_flash flash).html_safe %>
            </div>
            <div class="post">
              <%= yield %>
            </div>
          </div>
          <div id="sidebar">
            <h2>Users</h2>

            <% if signed_in? %>
            <ul>
                <li>
                    <%= link_to "My account" , user_path(current_user) %>
                </li>
                <li>
                    <%= link_to "Sign out" , sessions_destroy_path, method: "delete" %>
                </li>
            </ul>
            <% else %>
                <%= render 'sessions/form' %>
            <% end %>
          </div>
          <div style="clear: both;"></div>
        </div>
      </div>
    </div>
    <div class="footer">

    </div>
  </div>

</body>
</html>